apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pagamentos-ingress
  namespace: fase3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /pagamentos(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: pagamentos-service
                port:
                  number: 80
