apiVersion: v1
kind: ConfigMap
metadata:
  name: pagamentos-config
  namespace: fase3
data:
  DB_SERVER: "tcp:fase3-pagamentos-server.database.windows.net,1433"
  DB_NAME: "PagamentosDB"
  DB_ENCRYPT: "true"
  DB_TRUST_CERT: "false"
  DB_TIMEOUT: "30"


