apiVersion: v1
kind: ConfigMap
metadata:
  name: usuarios-config
  namespace: fase3
data:
  DB_SERVER: "tcp:fase3-usuarios-server.database.windows.net,1433"
  DB_NAME: "UsuariosDB"
  DB_ENCRYPT: "true"
  DB_TRUST_CERT: "false"
  DB_TIMEOUT: "30"


