apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jogos-ingress
  namespace: fase3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /jogos(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: jogos-service
                port:
                  number: 80

